spring:
  datasource:
    url: jdbc:postgresql://localhost:4008/history
    username: postgres
    password: password
  devtools:
    restart:
      poll-interval: 2s

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgresSQLDialect

  sql:
    init:
      mode: always